### ISSUE TITLE
Influx writes failing after migration to refactored code base

### ISSUE THREAD

**Issue by GrimmiMeloni** [solectrus/mqtt-collector#21]
Just gave the new codebase a spin.
After adjusting the environment to match the new names I am now seeing the following errors.

`Error while pushing to InfluxDB: failure writing points to database: partial write: field type conflict: input field "bat_fuel_charge" on measurement "SENEC" is type float, already exists as type integer dropped=1`

Was the change from integer to float intentional? 
If not, is there a quick fix apart from tossing all data?

**Comment by ledermann** [comment]
Thank you very much for giving this a go!

Indeed, the switch to float is intentional, sorry for the confusion. This is done to align with the existing format in SOLECTRUS. Additionally, it will render the graph less stepped.

I'm not familiar with a straightforward method to alter existing data types in InfluxDB. It might be possible to create a new bucket and transfer the data with the required conversion. However, it may be simpler to just erase the data and start over.

**Comment by GrimmiMeloni** [comment]
ACK.
Solved by copying data to new bucket while also converting the bat_fuel_charge to float.

```
from(bucket: "SENEC")
    |> range(start: 1970-01-01)
    |> filter(fn: (r) => r._measurement == "SENEC")
    |> filter(fn: (r) => r._field == "bat_fuel_charge")
    |> toFloat()
    |> to(bucket: "SENEC-NEW")
```

Followed by copying the rest of the data unchanged by

```
from(bucket: "SENEC")
    |> range(start: 1970-01-01)
    |> filter(fn: (r) => r._measurement == "SENEC")
    |> filter(fn: (r) => r._field != "bat_fuel_charge")
    |> to(bucket: "SENEC-NEW")
```

Used the InfluxUI then to rename the both buckets, turning the new bucket into the primary one used by the stack.

**Comment by ledermann** [comment]
Great job!
